# Generated by Django 4.2 on 2023-04-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upload/")),
                ("k", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
