# Generated by Django 4.2 on 2023-04-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_query_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
